theme: jekyll-theme-cayman
title: Intro and Intermediate Computing for Data Science
description: The programming brush-up course web-page for the Data Science Methodology MSc. at Barcelona School of Economics.